"""
pdf_generator.py — IRCTC-style Electronic Reservation Slip (ERS)
==================================================================
Drop-in replacement for the previous version. Same two function names/
signatures (fetch_booking_for_pdf, generate_irctc_ticket_pdf) so your
FastAPI endpoint (main.py's /api/download-ticket/{pnr}) needs no changes.

WHAT CHANGED VS. THE PREVIOUS VERSION, AND WHY:
  - fetch_booking_for_pdf now ALSO reads trains.csv/schedules.csv/
    stations.csv to fill in fields the DB alone can't provide:
      * Departure time (at source) / Arrival time (at destination) —
        pulled from schedules.csv for this train_number.
      * Distance (km) — estimated from station lat/lon (haversine
        straight-line distance). This is an ESTIMATE, not real IRCTC
        route-km — flagged in the PDF as approximate.
  - generate_irctc_ticket_pdf is rewritten to match the reference
    layout: circular logo placeholders, a "Booked From -> Boarding At
    -> To" row with an arrow graphic, a fare breakdown (ticket fare +
    convenience fee + insurance = total), a QR code encoding the PNR,
    a fabricated-but-realistic-looking GST/invoice block, and an
    acronym legend — all built with reportlab (canvas overlay for the
    logos/arrow/QR/watermark, Platypus tables for the data grids).

HONEST LIMITATIONS (please read before treating this as "real"):
  1. SPECIMEN WATERMARK: every ticket generated by this script is
     stamped "SPECIMEN — NOT A VALID TRAVEL DOCUMENT" diagonally across
     the page. This is a demo/portfolio project generating tickets from
     synthetic data, not real IRCTC — the watermark keeps that honest
     and prevents the output from being mistaken for (or misused as) a
     genuine ticket.
  2. NO REAL LOGOS: the "IR" / "IRCTC" roundels are plain stylized text
     in circles, not the actual official emblems — reproducing the real
     government/IRCTC logo artwork isn't something this script does.
  3. SINGLE PASSENGER ONLY: your bookings table stores one
     `passenger_name` + a `num_passengers` count per PNR — it has no
     per-passenger Age/Gender/name-list the way a real multi-passenger
     PNR does. The Age/Gender columns are rendered as "-" placeholders
     for this reason. If you want real multi-passenger tickets (2+
     named passengers, each with their own age/gender/seat), that needs
     a schema change: a separate `passengers` table keyed by
     pnr_number. Ask if you want that built.
  4. GSTIN / Invoice number / SAC code are FABRICATED placeholder
     values in a realistic format — not a real registered GSTIN.
  5. Distance is a straight-line estimate between station coordinates,
     not the actual rail route distance.

Install (adds qrcode + Pillow to your existing requirements):
    pip install reportlab qrcode pillow --break-system-packages

Data files expected next to this script (same folder as railway_code_cloud.py):
    pnr_bookings.db, trains.csv, schedules.csv, stations.csv
"""

import hashlib
import math
import os
import random

from io import BytesIO
from pathlib import Path

import pandas as pd
import qrcode
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.utils import ImageReader
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

DATA_DIR = Path(__file__).resolve().parent / "data"

# ----------------------------------------------------------------------
# Reference data (read-only) — used only to fill in fields the bookings
# table doesn't carry (departure/arrival time, distance).
# ----------------------------------------------------------------------
_trains_df = pd.read_csv(DATA_DIR / "trains.csv")
_schedules_df = pd.read_csv(DATA_DIR / "schedules.csv")
_stations_df = pd.read_csv(DATA_DIR / "stations.csv").set_index("station_code")


def _haversine_km(lat1, lon1, lat2, lon2):
    R = 6371.0
    phi1, phi2 = math.radians(lat1), math.radians(lat2)
    dphi = math.radians(lat2 - lat1)
    dlambda = math.radians(lon2 - lon1)
    a = math.sin(dphi / 2) ** 2 + math.cos(phi1) * math.cos(phi2) * math.sin(dlambda / 2) ** 2
    return 2 * R * math.asin(math.sqrt(a))


def _estimate_distance_km(source_code, destination_code):
    try:
        s = _stations_df.loc[source_code]
        d = _stations_df.loc[destination_code]
        return round(_haversine_km(s["latitude"], s["longitude"], d["latitude"], d["longitude"]))
    except KeyError:
        return None


def _lookup_timing(train_number, source_code, destination_code):
    """Returns (departure_time_str, arrival_time_str) from schedules.csv,
    or ('-', '-') if this train/station combo isn't in the schedule data."""
    stops = _schedules_df[_schedules_df["train_number"] == int(train_number)]
    dep_row = stops[stops["station_code"] == source_code]
    arr_row = stops[stops["station_code"] == destination_code]
    departure = dep_row.iloc[0]["departure"] if not dep_row.empty and pd.notna(dep_row.iloc[0]["departure"]) else "-"
    arrival = arr_row.iloc[0]["arrival"] if not arr_row.empty and pd.notna(arr_row.iloc[0]["arrival"]) else "-"
    # HH:MM:SS -> HH:MM for display
    departure = departure[:5] if departure != "-" else departure
    arrival = arrival[:5] if arrival != "-" else arrival
    return departure, arrival


def fetch_booking_for_pdf(pnr: str, bookings_conn=None) -> dict:
    """
    Fetches booking details from Supabase (via bookings_conn) for a given PNR,
    enriches them with timing (schedules.csv) and estimated distance (stations.csv),
    and maps everything to the dict format generate_irctc_ticket_pdf expects.
    """
    if bookings_conn is None:
        from railway_code_cloud import bookings_conn

    cur = bookings_conn.execute(
        "SELECT * FROM bookings WHERE pnr_number = ?", (pnr,)
    )
    raw_row = cur.fetchone()

    if not raw_row:
        raise ValueError(f"Booking with PNR {pnr} not found.")

    # Convert psycopg2 tuple row to dict using cursor description
    cols = [d[0] for d in cur.description]
    row = dict(zip(cols, raw_row))

    departure_time, arrival_time = _lookup_timing(
        row["train_number"], row["source_code"], row["destination_code"]
    )
    distance_km = _estimate_distance_km(row["source_code"], row["destination_code"])

    source_name = _stations_df.loc[row["source_code"], "station_name"] if row["source_code"] in _stations_df.index else row["source_code"]
    destination_name = _stations_df.loc[row["destination_code"], "station_name"] if row["destination_code"] in _stations_df.index else row["destination_code"]

    return {
        "pnr": row["pnr_number"],
        "train_number": str(row["train_number"]),
        "train_name": row["train_name"],
        "source": row["source_code"],
        "source_name": source_name,
        "destination": row["destination_code"],
        "destination_name": destination_name,
        "journey_date": row["journey_date"],
        "departure_time": departure_time,
        "arrival_time": arrival_time,
        "distance_km": distance_km,
        "class": row["class"],
        "booking_status": row["booking_status"],
        "current_status": row["current_status"],
        "coach": row["coach"] if row["coach"] else "Unassigned",
        "seat": row["seat_berth"] if row["seat_berth"] else "-",
        "berth_type": row["berth_type"] if row["berth_type"] else "-",
        "passenger_name": row["passenger_name"],
        "age": row.get("age") or "-",
        "gender": row.get("gender") or "-",
        "num_passengers": row["num_passengers"],
        "fare": row["fare_inr"],
        "booking_date": row["booking_date"],
    }


# ----------------------------------------------------------------------
# PDF generation
# ----------------------------------------------------------------------
def _fabricate_transaction_id(pnr: str) -> str:
    """Deterministic (same PNR -> same ID every time), not random, so
    re-downloading the same ticket doesn't show a different transaction
    ID each time. Clearly a placeholder format, not a real gateway ID."""
    digest = hashlib.sha256(pnr.encode()).hexdigest()
    return "1000" + str(int(digest[:8], 16))[-8:]


def _fabricate_invoice_and_gstin(pnr: str):
    digest = hashlib.sha256((pnr + "invoice").encode()).hexdigest()
    invoice_no = "PS" + str(int(digest[:10], 16))[-11:]
    gstin = f"07AAAGM{str(int(digest[10:16], 16))[-4:]}C1Z{digest[0].upper()}"
    return invoice_no, gstin


def _draw_page_decorations(canvas_obj, doc, data, qr_reader):
    """Called by SimpleDocTemplate on every page: watermark, logo
    roundels, header line, and QR code — everything that needs precise
    canvas positioning rather than flowing with the Platypus story."""
    canvas_obj.saveState()
    page_w, page_h = letter

    # --- SPECIMEN watermark (see HONEST LIMITATIONS at top of file) ---
    canvas_obj.setFont("Helvetica-Bold", 46)
    canvas_obj.setFillColor(colors.Color(0.85, 0.85, 0.85, alpha=0.55))
    canvas_obj.translate(page_w / 2, page_h / 2)
    canvas_obj.rotate(38)
    canvas_obj.drawCentredString(0, 0, "SPECIMEN — DEMO DATA")
    canvas_obj.rotate(-38)
    canvas_obj.translate(-page_w / 2, -page_h / 2)

    # --- Logo roundels (stylized placeholders, not real IR/IRCTC art) ---
    canvas_obj.setFillColor(colors.HexColor("#003366"))
    canvas_obj.circle(60, page_h - 55, 22, stroke=1, fill=1)
    canvas_obj.setFillColor(colors.white)
    canvas_obj.setFont("Helvetica-Bold", 9)
    canvas_obj.drawCentredString(60, page_h - 58, "IR")

    canvas_obj.setFillColor(colors.HexColor("#0B5FA4"))
    canvas_obj.circle(page_w - 60, page_h - 55, 22, stroke=1, fill=1)
    canvas_obj.setFillColor(colors.white)
    canvas_obj.drawCentredString(page_w - 60, page_h - 58, "IRCTC")

    # --- QR code, placed near the payment section ---
    canvas_obj.drawImage(
        qr_reader, page_w - 130, 195, width=80, height=80, preserveAspectRatio=True
    )

    canvas_obj.restoreState()


def generate_irctc_ticket_pdf(data: dict, output_pdf_path: str = "ticket.pdf"):
    """Generates an IRCTC-style Electronic Reservation Slip (ERS) PDF.
    See the HONEST LIMITATIONS note at the top of this file — this is a
    stylistic match for a portfolio/demo project, not a real ticket."""

    # Build the QR code once, up front, so the page-decoration callback
    # (which reportlab calls once per page) can just re-draw the same image.
    qr_payload = f"PNR:{data.get('pnr')}|TRAIN:{data.get('train_number')}|DATE:{data.get('journey_date')}"
    qr_img = qrcode.make(qr_payload)
    qr_buffer = BytesIO()
    qr_img.save(qr_buffer, format="PNG")
    qr_buffer.seek(0)
    qr_reader = ImageReader(qr_buffer)

    doc = SimpleDocTemplate(
        output_pdf_path,
        pagesize=letter,
        rightMargin=36,
        leftMargin=36,
        topMargin=70,
        bottomMargin=36,
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "IRCTCTitle", parent=styles["Heading1"], fontSize=13, leading=15,
        alignment=1, textColor=colors.HexColor("#003366"), fontName="Helvetica-Bold",
    )
    subtitle_style = ParagraphStyle(
        "IRCTCSubtitle", parent=styles["Normal"], fontSize=8.5, leading=10,
        alignment=1, textColor=colors.HexColor("#555555"),
    )
    route_style = ParagraphStyle(
        "IRCTCRoute", parent=styles["Normal"], fontSize=9.5, leading=13,
        alignment=1, textColor=colors.HexColor("#111111"),
    )
    route_bold = ParagraphStyle(
        "IRCTCRouteBold", parent=route_style, fontName="Helvetica-Bold", fontSize=11,
    )
    cell_style = ParagraphStyle(
        "IRCTCCell", parent=styles["Normal"], fontSize=9, leading=12,
        textColor=colors.HexColor("#222222"),
    )
    cell_bold = ParagraphStyle(
        "IRCTCCellBold", parent=cell_style, fontName="Helvetica-Bold",
    )
    table_header = ParagraphStyle(
        "IRCTCTableHeader", parent=styles["Normal"], fontSize=8.5, leading=11,
        textColor=colors.white, fontName="Helvetica-Bold", alignment=1,
    )
    small_gray = ParagraphStyle(
        "IRCTCSmallGray", parent=styles["Normal"], fontSize=6.8, leading=9,
        textColor=colors.HexColor("#666666"),
    )
    inst_style = ParagraphStyle(
        "IRCTCInst", parent=styles["Normal"], fontSize=7.5, leading=10,
        textColor=colors.HexColor("#555555"),
    )

    story = []

    # ---- Header ----
    story.append(Paragraph("Electronic Reservation Slip (ERS) — Normal User", title_style))
    story.append(Paragraph("Indian Railways Catering and Tourism Corporation (IRCTC)", subtitle_style))
    story.append(Spacer(1, 12))

    # ---- CANCELLED banner ----
    # A cancelled PNR still has its original coach/seat on record (cancel_ticket
    # only flips the status, it doesn't erase history) — so without a clear
    # visual flag, a cancelled ticket could be misread as a valid one at a
    # glance. This banner makes that impossible to miss.
    if data.get("current_status") == "CAN":
        cancelled_style = ParagraphStyle(
            "IRCTCCancelled", parent=styles["Normal"], fontSize=13, leading=16,
            alignment=1, textColor=colors.white, fontName="Helvetica-Bold",
        )
        t_cancelled = Table(
            [[Paragraph("THIS BOOKING HAS BEEN CANCELLED — NOT VALID FOR TRAVEL", cancelled_style)]],
            colWidths=[510],
        )
        t_cancelled.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#B91C1C")),
            ("TOPPADDING", (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ]))
        story.append(t_cancelled)
        story.append(Spacer(1, 10))

    # ---- Route row: Booked From -> Boarding At -> To (with arrow) ----
    source = data.get("source", "-")
    source_name = data.get("source_name", "")
    destination = data.get("destination", "-")
    destination_name = data.get("destination_name", "")
    journey_date = data.get("journey_date", "-")
    departure_time = data.get("departure_time", "-")
    arrival_time = data.get("arrival_time", "-")

    route_cells = [
        [
            Paragraph("Booked From", small_gray),
            Paragraph("&gt;&gt;&gt;  Boarding At  &gt;&gt;&gt;", small_gray),
            Paragraph("To", small_gray),
        ],
        [
            Paragraph(f"{source_name} ({source})", route_bold),
            Paragraph(f"{source_name} ({source})", route_bold),
            Paragraph(f"{destination_name} ({destination})", route_bold),
        ],
        [
            Paragraph(f"Start Date* {journey_date}", route_style),
            Paragraph(f"Departure* {departure_time} {journey_date}", route_style),
            Paragraph(f"Arrival* {arrival_time} {journey_date}", route_style),
        ],
    ]
    t_route = Table(route_cells, colWidths=[170, 170, 170])
    t_route.setStyle(TableStyle([
        ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#CBD5E1")),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
        ("BACKGROUND", (1, 0), (1, -1), colors.HexColor("#EAF2FB")),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(t_route)
    story.append(Spacer(1, 8))

    # ---- PNR / Train / Class / Quota / Distance / Booking Date grid ----
    distance_km = data.get("distance_km")
    distance_str = f"{distance_km} KM (approx., straight-line)" if distance_km else "-"

    grid = [
        [Paragraph(f"<b>PNR</b><br/>{data.get('pnr')}", cell_style),
         Paragraph(f"<b>Train No./Name</b><br/>{data.get('train_number')} / {data.get('train_name')}", cell_style),
         Paragraph(f"<b>Class</b><br/>{data.get('class')}", cell_style)],
        [Paragraph(f"<b>Quota</b><br/>General (GN)", cell_style),
         Paragraph(f"<b>Distance</b><br/>{distance_str}", cell_style),
         Paragraph(f"<b>Booking Date</b><br/>{data.get('booking_date')}", cell_style)],
    ]
    t_grid = Table(grid, colWidths=[170, 170, 170])
    t_grid.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F2F4F7")),
        ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#CBD5E1")),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(t_grid)
    story.append(Spacer(1, 12))

    # ---- Passenger Details ----
    story.append(Paragraph("<b>Passenger Details</b>", cell_bold))
    story.append(Spacer(1, 4))

    pass_headers = [
        Paragraph("S.No.", table_header), Paragraph("Name", table_header),
        Paragraph("Age", table_header), Paragraph("Gender", table_header),
        Paragraph("Booking Status", table_header), Paragraph("Current Status", table_header),
    ]
    # NOTE: this schema stores one passenger_name + a num_passengers COUNT,
    # not a per-passenger list — so only row 1 has real data. Age/Gender are
    # "-" because that data doesn't exist yet (see HONEST LIMITATIONS at top).
    pass_row = [
        Paragraph("1", cell_style),
        Paragraph(str(data.get("passenger_name")), cell_style),
        Paragraph(str(data.get("age", "-")), cell_style),
        Paragraph(str(data.get("gender", "-")), cell_style),
        Paragraph(str(data.get("booking_status")), cell_style),
        Paragraph(str(data.get("current_status")), cell_style),
    ]
    seat_line = Paragraph(
        f"Coach/Seat: {data.get('coach')} / {data.get('seat')} ({data.get('berth_type')})",
        small_gray,
    )
    t_pass = Table([pass_headers, pass_row], colWidths=[35, 150, 40, 55, 95, 95])
    t_pass.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#003366")),
        ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#003366")),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    story.append(t_pass)
    story.append(Spacer(1, 3))
    story.append(seat_line)
    story.append(Spacer(1, 6))

    story.append(Paragraph(
        "Acronyms: <b>RLWL</b>-Remote Location Waitlist &nbsp;&nbsp; "
        "<b>PQWL</b>-Pooled Quota Waitlist &nbsp;&nbsp; <b>RSWL</b>-Road-Side Waitlist",
        small_gray,
    ))
    story.append(Spacer(1, 10))

    # ---- Transaction + Payment ----
    txn_id = _fabricate_transaction_id(str(data.get("pnr")))
    story.append(Paragraph(f"<b>Transaction ID:</b> {txn_id}", cell_style))
    story.append(Spacer(1, 4))

    fare_base = float(data.get("fare") or 0)
    convenience_fee = round(fare_base * 0.035, 2)
    insurance_premium = 1.00
    total_fare = round(fare_base + convenience_fee + insurance_premium, 2)

    fare_rows = [
        [Paragraph("Ticket Fare", cell_style), Paragraph(f"Rs. {fare_base:,.2f}", cell_style)],
        [Paragraph("IRCTC Convenience Fee (Incl. of GST)", cell_style), Paragraph(f"Rs. {convenience_fee:,.2f}", cell_style)],
        [Paragraph("Travel Insurance Premium (Incl. of GST)", cell_style), Paragraph(f"Rs. {insurance_premium:,.2f}", cell_style)],
        [Paragraph("<b>Total Fare (all inclusive)</b>", cell_bold), Paragraph(f"<b>Rs. {total_fare:,.2f}</b>", cell_bold)],
    ]
    t_fare = Table(fare_rows, colWidths=[370, 140])
    t_fare.setStyle(TableStyle([
        ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#CBD5E1")),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
        ("LINEABOVE", (0, -1), (-1, -1), 1, colors.HexColor("#003366")),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("ALIGN", (1, 0), (1, -1), "RIGHT"),
    ]))
    story.append(t_fare)
    story.append(Spacer(1, 12))

    story.append(Paragraph(
        "PG Charges as applicable (Additional)",
        small_gray,
    ))
    story.append(Spacer(1, 10))

    # ---- Instructions ----
    instructions = (
        "<b>Important Instructions:</b><br/>"
        "1. One of the passengers booked on the PNR is required to present any of the identity cards "
        "noted above in original during the journey.<br/>"
        "2. Train departed/arrived status can be checked via RailBot AI or official IRCTC channels.<br/>"
        "3. This ticket is electronically generated and does not require a physical stamp.<br/>"
        "4. Beware of fraudulent customer care numbers — use only official IRCTC support channels.<br/>"
        "5. This document is a project demo and is not valid for actual travel."
    )
    story.append(Paragraph(instructions, inst_style))
    story.append(Spacer(1, 14))

    # ---- GST / Invoice block ----
    invoice_no, gstin = _fabricate_invoice_and_gstin(str(data.get("pnr")))
    gst_rows = [
        [Paragraph("<b>Indian Railways GST Details</b>", cell_bold), ""],
        [Paragraph("Invoice Number", small_gray), Paragraph(invoice_no, cell_style)],
        [Paragraph("Address", small_gray), Paragraph("Indian Railways, New Delhi", cell_style)],
        [Paragraph("Supplier SAC Code", small_gray), Paragraph("996421", cell_style)],
        [Paragraph("Supplier GSTIN", small_gray), Paragraph(gstin, cell_style)],
        [Paragraph("Recipient", small_gray), Paragraph(str(data.get("passenger_name")), cell_style)],
    ]
    t_gst = Table(gst_rows, colWidths=[150, 360])
    t_gst.setStyle(TableStyle([
        ("SPAN", (0, 0), (1, 0)),
        ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#CBD5E1")),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(t_gst)

    # QR code and logos/watermark are canvas overlays, drawn once per page.
    on_page = lambda c, d: _draw_page_decorations(c, d, data, qr_reader)
    doc.build(story, onFirstPage=on_page, onLaterPages=on_page)
